/* SPDX-License-Identifier: MIT */
/*
 * Copyright (C) 2025 Intel Corporation
 */

#ifndef __INTEL_CMTG_REGS_H__
#define __INTEL_CMTG_REGS_H__

#include "intel_display_reg_defs.h"

#define CMTG_CLK_SEL			_MMIO(0x46160)
#define CMTG_CLK_SEL_A_MASK		REG_GENMASK(31, 29)
#define CMTG_CLK_SELECT_PHYA_ENABLE	REG_FIELD_PREP(CMTG_CLK_SEL_A_MASK, 0x4)
#define CMTG_CLK_SEL_A_DISABLED		REG_FIELD_PREP(CMTG_CLK_SEL_A_MASK, 0)
#define CMTG_CLK_SEL_B_MASK		REG_GENMASK(15, 13)
#define CMTG_CLK_SELECT_PHYB_ENABLE	REG_FIELD_PREP(CMTG_CLK_SEL_B_MASK, 0x6)
#define CMTG_CLK_SEL_B_DISABLED		REG_FIELD_PREP(CMTG_CLK_SEL_B_MASK, 0)

#define _TRANS_CMTG_CTL_A		0x6fa88
#define _TRANS_CMTG_CTL_B		0x6fb88
#define TRANS_CMTG_CTL(trans)		_MMIO_TRANS((trans), \
						    _TRANS_CMTG_CTL_A, _TRANS_CMTG_CTL_B)
#define  CMTG_ENABLE			REG_BIT(31)
#define  CMTG_SYNC_TO_PORT		REG_BIT(29)

#endif /* __INTEL_CMTG_REGS_H__ */
